version: "3"
services:

   deli_grafana_label:
      image: deli_grafana_image
      container_name: deli_grafana_container
      build: ./services/grafana
      env_file:
         - .private/grafana.env
      ports:
         - ${DELI_GRAFANA_PORT}:3000
      volumes:
         - deli_grafana_volume:/var/lib/grafana
         - ./shared/grafana/:/usr/share/grafana/conf/provisioning/

   deli_db_label:
      image: deli_db_image
      container_name: deli_db_container
      build: ./services/postgres
      env_file:
         - .private/postgres.env
      ports:
         - ${DELI_POSTGRES_PORT}:5432
      volumes:
         - deli_pgdata_volume:/var/lib/postgresql/data

   deli_apache_label:
      image: deli_apache_image
      build: ./services/apache
      container_name: deli_apache_container
      ports:
         - ${DELI_APACHE_PORT}:80
      volumes:
         - ./html/:/usr/local/apache2/htdocs/:ro
        #  - ./html/:/var/www/html/:ro

volumes:
   deli_grafana_volume: {}
   deli_pgdata_volume: {}

networks:
   datalake_main_network: {}
