version: "3"
services:

   deli_grafana_label:
      image: deli_grafana_image
      container_name: deli_grafana_container
      build: ./services/grafana
      env_file:
         - .private/grafana.env
      ports:
         - ${DELI_GRAFANA_PORT}:3000
      volumes:
         - deli_grafana_volume:/var/lib/grafana
         - ./shared/grafana/:/usr/share/grafana/conf/provisioning/
      networks:
         - deli_main_network

   deli_db_label:
      image: deli_db_image
      container_name: deli_db_container
      build: ./services/postgres
      env_file:
         - .private/postgres.env
      ports:
         - ${DELI_POSTGRES_PORT}:5432
      volumes:
         - deli_pgdata_volume:/var/lib/postgresql/data
      networks:
         - deli_main_network

   deli_node_label:
      image: deli_node_image
      container_name: deli_node_container
      build:
         context: ./services/node
      ports:
         - ${DELI_NODE_PORT}:${NODE_PORT}
      env_file:
         - .private/node.env
      volumes: 
         - ./app:/app
      networks:
         - deli_main_network

   deli_ubuntu_label:
      image: deli_ubuntu_image
      container_name: deli_ubuntu_container
      build: ./services/ubuntu
      env_file:
         - .private/ubuntu.env
      # ports:
      #    - 8000:8000
      #    - 5173:5173
      volumes:
         - ./app:/app
      networks:
         - deli_main_network
      # environment:
      #    - GK_PWD=${PWD}
      #    - NODE_PORT=${NODE_PORT}

volumes:
   deli_grafana_volume: {}
   deli_pgdata_volume: {}

networks:
   deli_main_network: {}
