version: '3.8'

services:
   test_mysql_container:
      image: mysql:latest
      container_name: test_mysql_container
      restart: always
      environment:
         MYSQL_ROOT_PASSWORD: 1234
         MYSQL_DATABASE: test_main_database
         MYSQL_USER: george
         MYSQL_PASSWORD: 4321
      ports:
         - "3306:3306"
      volumes:
         - ./shared/mysql:/var/lib/mysql
      # networks:
      #    - test_main_network

   test_ubuntu_container:
      image: ubuntu:latest
      container_name: test_ubuntu_container
      restart: always
      command: tail -f /dev/null
      tty: true
      stdin_open: true
      # networks:
      #    - test_main_network

# networks:
#    test_main_network:
#       driver: bridge
