version: "3.9"

networks:
  main_network:
    name: ${PROJECT_NAME}_main_network

services:
  # React Production App
  node_label:
    build:
      context: ./services/node
    container_name: ${PROJECT_NAME}_node_container
    restart: unless-stopped
    networks:
      - main_network

  # Express backend
  express_label:
    build:
      context: ./services/express
    container_name: ${PROJECT_NAME}_express_container
    ports:
      - 8435:9080
    restart: unless-stopped
    networks:
      - main_network
    depends_on:
      - db_label
    environment:
      SERVICE_NAME: ${SERVICE_NAME}
      SERVICE_PASSWORD: ${SERVICE_PASSWORD}

  # PostgreSQL
  db_label:
    image: postgres:17
    container_name: ${PROJECT_NAME}_db_container
    env_file:
      - ./services/postgres/.env
    restart: unless-stopped
    networks:
      - main_network

  # Grafana
  grafana_label:
    image: grafana/grafana:11.5.2
    container_name: ${PROJECT_NAME}_grafana_container
    user: "472:472"
    env_file:
      - ./services/grafana/.env
    ports:
      - "${HOST_GRAFANA_PORT}:3000"
    restart: unless-stopped
    volumes:
      - ./shared/grafana:/var/lib/grafana
      - ./app-grafana:${GLOBAL_GF_PATHS_PROVISIONING}
    networks:
      - main_network
    depends_on:
      - db_label

  # Nginx Proxy Manager is managed separately — not in this compose file.
