version: "3"
services:

   deli_main_label:
      container_name: deli_main_container
      build: ./services/grafana
      # image: grafana/grafana-oss
      environment:
         # grafana setting to allow embedding
         GF_SECURITY_ALLOW_EMBEDDING: 'true'
         # grafana setting to allow anonymous usage
         GF_AUTH_ANONYMOUS_ENABLED: 'true'
      ports:
         - 3000:3000
      volumes:
         - deli_main_volume:/var/lib/grafana
         - ./shared/grafana/:/usr/share/grafana/conf/provisioning/

   deli_db_label:
      container_name: deli_db_container
      build: ./services/postgres
      # image: postgres
      ports:
         - 5432:5432
      restart: always
      environment:
         POSTGRES_PASSWORD: admin
      volumes:
         - deli_pgdata_volume:/var/lib/postgresql/data
         

   deli_frontend_label:
      build: ./services/apache
      container_name: deli_frontend_container
      ports:
         - 9080:80
      volumes:
         - ./html/:/usr/local/apache2/htdocs/:ro
        #  - ./html/:/var/www/html/:ro

volumes:
   deli_main_volume: {}
   deli_pgdata_volume: {}
