# Reference
# https://grafana.com/docs/grafana/latest/administration/provisioning/?utm_source=grafana_ds_list#data-sources

# https://grafana.com/docs/grafana/latest/datasources/postgres/
# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
- name: george_test_datasource
   orgId: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
# <string, required> Sets the name you use to refer to
# the data source in panels and queries.
-  name: george_test_datasource
   # <string, required> Sets the data source type.
   type: PostgreSQL
   # <string, required> Sets the access mode, either
   # proxy or direct (Server or Browser in the UI).
   # Some data sources are incompatible with any setting
   # but proxy (Server).
   access: proxy
   # <int> Sets the organization id. Defaults to orgId 1.
   orgId: 1
   # <string> Sets a custom UID to reference this
   # data source in other parts of the configuration.
   # If not specified, Grafana generates one.
   uid: my_unique_uid
   # <string> Sets the data source's URL, including the
   # port.
   url: deli_db_label:5432
   # <string> Sets the database user, if necessary.
   user: postgres
   # # <string> Sets the database name, if necessary.
   # database: deli_db
   # <bool> Enables basic authorization.
   basicAuth: false
   # <string> Sets the basic authorization username.
   basicAuthUser: postgres

   # <bool> Enables credential headers.
   # withCredentials:

   # <bool> Toggles whether the data source is pre-selected
   # for new panels. You can set only one default
   # data source per organization.
   isDefault: true
   # <map> Fields to convert to JSON and store in jsonData.
   jsonData:
      database: "deli_db"
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1600
   # <map> Fields to encrypt before storing in jsonData.
   secureJsonData:
      password: 'admin'

   #    # <string> Defines the CA cert, client cert, and
   #    # client key for encrypted authentication.
   #    tlsCACert: '...'
   #    tlsClientCert: '...'
   #    tlsClientKey: '...'
   #    # <string> Sets the database password, if necessary.
   #    password:
   #    # <string> Sets the basic authorization password.
   #    basicAuthPassword:
   # <int> Sets the version. Used to compare versions when
   # updating. Ignored when creating a new data source.
   version: 1
   # <bool> Allows users to edit data sources from the
   # Grafana UI.
   editable: true