{
 "title": "deli_main_dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "deli_custom_var", "label": "deli_custom_label" },
   {
    "name": "country_filter",
    "query": "Greece, Romania, Lithuania, Belgium, Italy, Spain"
   },
   { "name": "minyear_filter", "query": "1990" },
   { "name": "maxyear_filter", "query": "2020" },
   { "name": "factor_filter", "query": "Rate_SEV_val" },
   { "name": "policy_filter", "query": "Mental Health" },
   { "name": "riskFactor_filter", "query": "Alcohol use" },
   { "name": "yearLag_filter", "query": "1" },
   { "name": "sex_filter", "query": "Both" },
   { "name": "age_filter", "query": "Age-standardized" },
   { "name": "diet_type_filter", "query": "Diet low in whole grains" },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Predictive Analytics",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \r\n   *\r\nFROM predictive_tbl\r\nWHERE true\r\n-- AND \"Year Lag\" = '1'\r\n   AND \"Risk Factor\" = '${riskFactor_filter}'\r\n;"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n   \"Country\",\n   AVG(\"Diet low in whole grains_${factor_filter}\") AS \"Diet low in whole grains\",\n   AVG(\"Diet low in milk_${factor_filter}\") AS \"Diet low in milk\",\n   AVG(\"Diet high in red meat_${factor_filter}\") AS \"Diet high in red meat\",\n   AVG(\"Diet low in calcium_${factor_filter}\") AS \"Diet low in calcium\",\n   AVG(\"Diet low in fiber_${factor_filter}\") AS \"Diet low in fiber\",\n   AVG(\"Diet high in processed meat_${factor_filter}\") AS \"Diet high in processed meat\"\n   -- AVG(\"Diet low in fruits_${factor_filter}\") AS \"Diet low in fruits\",\n   -- AVG(\"Diet low in vegetables_${factor_filter}\") AS \"Diet low in vegetables\",\nFROM data_tbl\nWHERE true\n   AND \"Country\" IN ('Greece', 'Romania', 'Lithuania', 'Belgium', 'Italy', 'Spain')\n   -- AND \"Year\" BETWEEN ${minyear_filter} AND ${maxyear_filter}\n   AND \"age\" = 'Age-standardized'\nGROUP BY \"Country\"\nORDER BY 1\n;"
    }
   ]
  },
  {
   "title": "Predictive Analytics - Per Year Lag",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n   *\r\nFROM predictive_tbl\r\nWHERE true\r\n AND \"Year Lag\" = '${yearLag_filter}'\r\n   --AND \"Risk Factor\" = '${riskFactor_filter}'\r\n;"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n   \"Country\",\n   AVG(\"Alcohol use_${factor_filter}\") AS \"Alcohol Use\",\n   AVG(\"Smoking_${factor_filter}\") AS \"Smoking\",\n   AVG(\"Low physical activity_${factor_filter}\") AS \"Low Physical Activity\",\n   AVG(\"High body-mass index_${factor_filter}\") AS \"High Body-Mass Index\"\nFROM data_tbl\nWHERE true\n   AND \"Country\" IN (\n   'Belgium', 'Greece', 'Italy', 'Lithuania', 'Romania', 'Spain', \n   'Andorra', 'Cyprus', 'Turkey', 'Switzerland', 'Hungary', 'Luxembourg', \n   'Sweden', 'Norway', 'Belarus', 'United Kingdom', 'Russian Federation', \n   'Netherlands', 'Montenegro', 'Austria', 'Ireland', 'Germany', 'Serbia', \n   'Portugal', 'Finland', 'Malta', 'Albania', 'Ukraine', 'Bulgaria', \n   'Croatia', 'Latvia', 'England', 'Slovenia', 'North Macedonia', 'France', \n   'Estonia', 'Slovakia', 'Monaco', 'Israel', 'Poland', 'Iceland', \n   'Republic of Moldova', 'Denmark', 'Bosnia and Herzegovina', 'Czechia')\n   AND \"Year\" BETWEEN ${minyear_filter} AND ${maxyear_filter}\n   AND \"age\" = 'Age-standardized'\nGROUP BY \"Country\"\nORDER BY 1\n;\n"
    }
   ]
  },
  {
   "title": "Risk Factor Exposure",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n   \"Year\" as year_str,\n   \"Country\" as country_str,\n   AVG(\"Diet low in whole grains_${factor_filter}\") AS \"Diet low in whole grains\",\n   --AVG(\"Diet low in whole grains_${factor_filter}\") AS \"Diet low in whole grains\",\n   AVG(\"Diet low in milk_${factor_filter}\") AS \"Diet low in milk\",\n   AVG(\"Diet high in red meat_${factor_filter}\") AS \"Diet high in red meat\",\n   AVG(\"Diet low in calcium_${factor_filter}\") AS \"Diet low in calcium\",\n   AVG(\"Diet low in fiber_${factor_filter}\") AS \"Diet low in fiber\",\n   AVG(\"Diet high in processed meat_${factor_filter}\") AS \"Diet high in processed meat\"\n   -- AVG(\"Diet low in fruits_${factor_filter}\") AS \"Diet low in fruits\",\n   -- AVG(\"Diet low in vegetables_${factor_filter}\") AS \"Diet low in vegetables\",\nFROM data_tbl\nWHERE true\n   AND \"Country\" IN ('Belgium', 'Greece', 'Italy', 'Lithuania', 'Romania', 'Spain', \n   'Andorra', 'Cyprus', 'Turkey', 'Switzerland', 'Hungary', 'Luxembourg', \n   'Sweden', 'Norway', 'Belarus', 'United Kingdom', 'Russian Federation', \n   'Netherlands', 'Montenegro', 'Austria', 'Ireland', 'Germany', 'Serbia', \n   'Portugal', 'Finland', 'Malta', 'Albania', 'Ukraine', 'Bulgaria', \n   'Croatia', 'Latvia', 'England', 'Slovenia', 'North Macedonia', 'France', \n   'Estonia', 'Slovakia', 'Monaco', 'Israel', 'Poland', 'Iceland', \n   'Republic of Moldova', 'Denmark', 'Bosnia and Herzegovina', 'Czechia')\n   AND \"Year\" BETWEEN ${minyear_filter} AND ${maxyear_filter}\n   AND \"sex\" = '${sex_filter}'\n   AND \"age\" = '${age_filter}'\n  GROUP BY\n      \"Country\",\n      \"Year\"\nORDER BY 1,2\n;"
    }
   ]
  },
  {
   "title": "Risk Factor Exposure - Lifestyle",
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n   \"Year\" as year_str,\n   \"Country\" as country_str,\n   AVG(\"Alcohol use_${factor_filter}\") AS \"Alcohol use\",\n   AVG(\"Smoking_${factor_filter}\") AS \"Smoking\",\n   AVG(\"Low physical activity_${factor_filter}\") AS \"Low Physical Activity\",\n   AVG(\"High body-mass index_${factor_filter}\") AS \"High Body-Mass Index\"\nFROM data_tbl\nWHERE true\n   AND \"Country\" IN ('Belgium', 'Greece', 'Italy', 'Lithuania', 'Romania', 'Spain', \n   'Andorra', 'Cyprus', 'Turkey', 'Switzerland', 'Hungary', 'Luxembourg', \n   'Sweden', 'Norway', 'Belarus', 'United Kingdom', 'Russian Federation', \n   'Netherlands', 'Montenegro', 'Austria', 'Ireland', 'Germany', 'Serbia', \n   'Portugal', 'Finland', 'Malta', 'Albania', 'Ukraine', 'Bulgaria', \n   'Croatia', 'Latvia', 'England', 'Slovenia', 'North Macedonia', 'France', \n   'Estonia', 'Slovakia', 'Monaco', 'Israel', 'Poland', 'Iceland', \n   'Republic of Moldova', 'Denmark', 'Bosnia and Herzegovina', 'Czechia')\n   AND \"Year\" BETWEEN ${minyear_filter} AND ${maxyear_filter}\n   AND \"sex\" = '${sex_filter}'\n   AND \"age\" = '${age_filter}'\n  GROUP BY\n      \"Country\",\n      \"Year\"\nORDER BY 1,2\n;"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "CREATE EXTENSION IF NOT EXISTS tablefunc;\n\nSELECT \n   *\nFROM crosstab('\n   SELECT \n      \"Year\" as year_str,\n      \"Country\" as country_str,\n      AVG(\"CRC_incidence_val_Rate\") as values_f\n   FROM data_tbl \n   WHERE true\n      AND \"Year\" BETWEEN ${minyear_filter} AND ${maxyear_filter}\n      AND \"age\" = ''${age_filter}''\n      AND \"sex\" = ''${sex_filter}''\n   GROUP BY\n      \"Country\",\n      \"Year\"\n   ORDER BY 1, 2\n',\n'\nSELECT * FROM unnest(ARRAY[\n   ''Belgium'', ''Greece'', ''Italy'', ''Lithuania'', ''Romania'', ''Spain'', \n   ''Andorra'', ''Cyprus'', ''Turkey'', ''Switzerland'', ''Hungary'', ''Luxembourg'', \n   ''Sweden'', ''Norway'', ''Belarus'', ''United Kingdom'', ''Russian Federation'', \n   ''Netherlands'', ''Montenegro'', ''Austria'', ''Ireland'', ''Germany'', ''Serbia'', \n   ''Portugal'', ''Finland'', ''Malta'', ''Albania'', ''Ukraine'', ''Bulgaria'', \n   ''Croatia'', ''Latvia'', ''England'', ''Slovenia'', ''North Macedonia'', ''France'', \n   ''Estonia'', ''Slovakia'', ''Monaco'', ''Israel'', ''Poland'', ''Iceland'', \n   ''Republic of Moldova'', ''Denmark'', ''Bosnia and Herzegovina'', ''Czechia''\n]) AS country_str\n'\n) AS ct (\n   \"Year\" INT,\n   \"Belgium\" DOUBLE PRECISION,\n   \"Greece\" DOUBLE PRECISION,\n   \"Italy\" DOUBLE PRECISION,\n   \"Lithuania\" DOUBLE PRECISION,\n   \"Romania\" DOUBLE PRECISION,\n   \"Spain\" DOUBLE PRECISION,\n   \"Andorra\" DOUBLE PRECISION,\n   \"Cyprus\" DOUBLE PRECISION,\n   \"Turkey\" DOUBLE PRECISION,\n   \"Switzerland\" DOUBLE PRECISION,\n   \"Hungary\" DOUBLE PRECISION,\n   \"Luxembourg\" DOUBLE PRECISION,\n   \"Sweden\" DOUBLE PRECISION,\n   \"Norway\" DOUBLE PRECISION,\n   \"Belarus\" DOUBLE PRECISION,\n   \"United Kingdom\" DOUBLE PRECISION,\n   \"Russian Federation\" DOUBLE PRECISION,\n   \"Netherlands\" DOUBLE PRECISION,\n   \"Montenegro\" DOUBLE PRECISION,\n   \"Austria\" DOUBLE PRECISION,\n   \"Ireland\" DOUBLE PRECISION,\n   \"Germany\" DOUBLE PRECISION,\n   \"Serbia\" DOUBLE PRECISION,\n   \"Portugal\" DOUBLE PRECISION,\n   \"Finland\" DOUBLE PRECISION,\n   \"Malta\" DOUBLE PRECISION,\n   \"Albania\" DOUBLE PRECISION,\n   \"Ukraine\" DOUBLE PRECISION,\n   \"Bulgaria\" DOUBLE PRECISION,\n   \"Croatia\" DOUBLE PRECISION,\n   \"Latvia\" DOUBLE PRECISION,\n   \"England\" DOUBLE PRECISION,\n   \"Slovenia\" DOUBLE PRECISION,\n   \"North Macedonia\" DOUBLE PRECISION,\n   \"France\" DOUBLE PRECISION,\n   \"Estonia\" DOUBLE PRECISION,\n   \"Slovakia\" DOUBLE PRECISION,\n   \"Monaco\" DOUBLE PRECISION,\n   \"Israel\" DOUBLE PRECISION,\n   \"Poland\" DOUBLE PRECISION,\n   \"Iceland\" DOUBLE PRECISION,\n   \"Republic of Moldova\" DOUBLE PRECISION,\n   \"Denmark\" DOUBLE PRECISION,\n   \"Bosnia and Herzegovina\" DOUBLE PRECISION,\n   \"Czechia\" DOUBLE PRECISION\n)\nORDER BY ct.\"Year\";\n"
    }
   ]
  },
  {
   "type": "volkovlabs-echarts-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n   \"Country\",\n   \"Type\"\nFROM policies_tbl\nWHERE true\n   AND \"Policy\" = '${policy_filter}'\n   AND \"Comment\" != ''\n;\n"
    },
    {
     "rawSql": "SELECT\n   DISTINCT \"Country\"\nFROM policies_tbl\nORDER BY \"Country\"\n;\n"
    },
    {
     "rawSql": "SELECT\r\n   \"Country\",\r\n   coalesce(\"Comment\", 'None') as \"Comment\"\r\nFROM policies_tbl\r\nWHERE true\r\n   AND \"Type\" = 'Best Practices'\r\n   AND \"Policy\" = '${policy_filter}'\r\n   AND \"Comment\" != ''\r\n;\r\n"
    }
   ]
  }
 ]
}