FROM httpd:2.4
# COPY ./public-html/ /usr/local/apache2/htdocs/

# FROM ubuntu 
# EXPOSE 80

# RUN cp -r /shared/* /var/www/html/

# RUN apt update 
# RUN apt install -y apache2 apache2-utils 
# RUN apt clean 
# CMD ["apache2ctl", "-D", "FOREGROUND"]